name: dup
description: "A powerful, flexible schema-based validation library for Dart, inspired by JavaScript's yup."
version: 2.0.0
homepage: https://github.com/muminjun/dup
repository: https://github.com/muminjun/dup

environment:
  sdk: ^3.7.2

dependencies: {}

dev_dependencies:
  test: ^1.25.0
  lints: ^5.0.0
